### PR TITLE
Fix dispose called on null during ClientHandler disposal

### LINKED ISSUE #823: JS error when NaCl crashes and there's active client
Just observed this on a test device after the Connector's NaCl module crashed (for an unrelated reason):

```
Uncaught TypeError: Cannot read properties of null (reading 'g')
    at I (background.js:101:481)
    at kl.A (background.js:456:49)
    at I (background.js:101:494)
    at background.js:457:296
    at H.A (background.js:101:911)
    at fl.A (background.js:451:41)
    at I (background.js:101:494)
    at background.js:450:325
    at H.A (background.js:101:911)
    at h.A (background.js:178:175)
```

The stack trace is obfuscated due to minification, but after comparing the minified and original code I think it's crashing in `ClientHandler.disposeInternal()`: https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/blob/f4eb32264c2c2b7afe57db0cf8ee280c98ce9ae3/third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js#L211

### PR DESCRIPTION
**Pull request by ViktoriiaKovalova**
This fixes #823.

### CODE REVIEW

**Comment by emaxx-google** [comment]
I'm wondering now whether the `this.serverRequester_ = null` assignment is needed in the first place. Can't we just drop it?

File: third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js [hunk 1]
```diff
@@ -301,11 +302,6 @@ ClientHandler.prototype.serverRequesterDisposedListener_ = function() {
   if (this.isDisposed())
```
Comment (emaxx-google) [inline third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js:302]: nit: This check is not needed anymore as well.

File: third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js [hunk 2]
```diff
@@ -183,7 +183,9 @@ Pcsc.ServerRequestHandler = class extends goog.Disposable {
 
   /** @override */
   disposeInternal() {
-    super.disposeInternal();
+    if (this.isDisposed()) {
```
[the remark this answers is not in the document]
Comment (ViktoriiaKovalova) [reply third_party/pcsc-lite/naclport/server_clients_management/src/server-request-handler.js]: thanks!

File: third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js (hunk 1 above)
Comment (ViktoriiaKovalova) [reply third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js:302]: I don't understand this. Why?

Comment (emaxx-google) [reply third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js:302]: We can just call `this.dispose()`. Same as in the other comment thread, it can be called multiple times, but it does internal bookkeeping in order to call `disposeInternal()` only once.

Comment (ViktoriiaKovalova) [reply third_party/pcsc-lite/naclport/server_clients_management/src/client-handler.js]: ah, thanks, i was looking at the wrong part of the code

**Comment by emaxx-google** [comment]
Thanks for the fix. Let me take a quick look at how we could test this kind of regression fix. This piece of code currently doesn't have test coverage, so I'll try to write the first example.

**Comment by emaxx-google** [comment]
Alright, so with #831 landed I think it should be possible to write a regression test. The test would create the client handler (similarly to `testSmoke`), then shut down `mockServerMessageChannel` and verify the client handler got disposed of.

**Comment by ViktoriiaKovalova** [comment]
I added tests and checked that testServerChannelDisposed breaks without this change :)

File: third_party/pcsc-lite/naclport/server_clients_management/src/client-handler-unittest.js [hunk 3]
```diff
@@ -69,5 +70,35 @@ goog.exportSymbol('testClientHandler', {
 
     handler.dispose();
   },
+
+  'testClientChannelDisposed': function() {
+    const handler = new ClientHandler(
+        mockServerMessageChannel, goog.Promise.resolve(),
+        mockClientMessageChannel, EXTENSION_ID_A);
+    mockClientMessageChannel.dispose();
```
Comment (emaxx-google) [inline third_party/pcsc-lite/naclport/server_clients_management/src/client-handler-unittest.js:78]: nit: Maybe extract this into a separate function? This `.dispose()` together with the `disposeInternal` hack.

File: third_party/pcsc-lite/naclport/server_clients_management/src/client-handler-unittest.js [hunk 4]
```diff
@@ -69,5 +70,35 @@ goog.exportSymbol('testClientHandler', {
...
+    // Hack: call the protected disposeInternal() method in order to trigger the
+    // disposal notifications; the MockMessageChannel.dispose() doesn't call
+    // them.
+    mockClientMessageChannel[goog.reflect.objectProperty(
+        'disposeInternal', mockClientMessageChannel)]();
+    assert(
```
Comment (emaxx-google) [inline third_party/pcsc-lite/naclport/server_clients_management/src/client-handler-unittest.js:84]: nit: `goog.require` `goog.asserts`

**Comment by emaxx-google** [comment]
Thank you! Looks good modulo nits.

**Review by emaxx-google — CHANGES_REQUESTED** [review]

**Review by emaxx-google — APPROVED** [review]

File: third_party/pcsc-lite/naclport/server_clients_management/src/client-handler-unittest.js [hunk 5]
```diff
@@ -17,7 +17,9 @@
 
 goog.require('GoogleSmartCard.PcscLiteServerClientsManagement.ClientHandler');
 goog.require('goog.Promise');
+goog.require('goog.reflect');
 goog.require('goog.testing');
+goog.require('goog.testing.asserts');
```
Comment (emaxx-google) [inline third_party/pcsc-lite/naclport/server_clients_management/src/client-handler-unittest.js:22]: nit: Swap this with the next line, to keep directives sorted.

Comment (ViktoriiaKovalova) [reply third_party/pcsc-lite/naclport/server_clients_management/src/client-handler-unittest.js]: oops, fixed
