### PR TITLE
Detect crash loops

### LINKED ISSUE #156: Detect and exit crash-and-restart loops
Currently, the Smart Card Connector app reloads itself in case a fatal error (e.g., inability to load the NaCl module or the absence of expected Extension APIs) occurs. This is done in the hope that the app will "self-repair" itself and continue serving user purposes - for instance, in case the crash was caused by some unexpected combination of internal operations, new operations after the restart will likely run in a different order and combination.

The problem with this approach is that sometimes there are unrepairable errors (for example, due to a bug somewhere or a misconfigured device), and in this case the app will end up reloading itself again and again, until Chrome disables the app with the "This extension reloaded itself too frequently" error. The worst thing about this scenario is that there's no way to obtain the app's logs, meaning that the troubleshooting and investigation of bug reports is extremely difficult.

The proposal is to suppress the self-reload functionality in case the crash-and-restart loop is detected (most likely, heuristically).

### PR DESCRIPTION
**Pull request by emaxx-google**
Store the recent crash timestamps of the Smart Card Connector app in the
chrome.storage.local data, and skip reloading itself on fatal error in
case this data shows that the reloads have been happening frequently.

This fixes #156.

### CODE REVIEW

**Comment by emaxx-google** [comment]
Still working on unit tests for this.

File: common/js/src/logging/crash-loop-detection.js [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+        -CRASH_LOOP_THRESHOLD_COUNT + 1);
+  }
+  newCrashTimestamps.push(currentTimestamp);
+
+  if (!chrome || !chrome.storage || !chrome.storage.local) {
+    // Cannot store any data without access to the chrome.storage API.
+    return Promise.resolve(newCrashTimestamps);
+  }
+  return new Promise(resolve => {
+    chrome.storage.local.set({[STORAGE_KEY]: newCrashTimestamps}, function() {
```
Comment (Fabian-Sommer) [inline common/js/src/logging/crash-loop-detection.js:116]: Question: Why is STORAGE_KEY inside [] here?

File: common/js/src/logging/logging.js [hunk 2]
```diff
@@ -201,23 +202,18 @@ GSC.Logging.checkWithLogger = function(
...
- * Fails with the specified message.
-  *
- * In the debug mode, this function effectively throws an instance of
- * goog.asserts.AssertionError.
+ * Throws an exception and emits severe log with the specified message.
  *
- * In the release mode, this function emits severe log message and initiates the
- * App reload.
+ * In the release mode, this additionally asynchronously initiates the App
+ * reload, unless the crash-and-reload loop is detected.
```
Comment (Fabian-Sommer) [inline common/js/src/logging/logging.js:208]: nit: replace 'the' with 'a'

File: common/js/src/logging/crash-loop-detection.js [hunk 3]
```diff
@@ -0,0 +1,132 @@
...
+const STORAGE_KEY = 'crash_timestamps';
+
+// The time window, during which the crashes are counted and compared against
+// |CRASH_LOOP_THRESHOLD_COUNT|.
+const CRASH_LOOP_WINDOW_MILLISECONDS = 60 * 1000;
+// If the number of crashes reaches this constant within the
+// |CRASH_LOOP_WINDOW_MILLISECONDS| time window, then it's considered to be a
+// crash loop.
+//
+// Note that these two constants have to be chosen to be stricter than the
```
[the remark this answers is not in the document]
Comment (emaxx-google) [reply common/js/src/logging/crash-loop-detection.js]: Maybe I'm confusing something, but I think that a longer time window is stricter than a shorter one? I.e., the sequence of crashes "t=0, t=12, t=24, t=36, t=48" is a violation in the "window=60" configuration, but not in the "window=10" one.

P.S. Replaced "two constants" with their names, to avoid confusion.

File: common/js/src/logging/crash-loop-detection.js (hunk 1 above)
Comment (emaxx-google) [reply common/js/src/logging/crash-loop-detection.js]: It's the JS syntax (introduced in ECMAScript2015) that means "read the STORAGE_KEY's value", rather than "literally use the `"STORAGE_KEY"` string".

But I've replaced it with a separate object construction, so that there's no confusion.

**Comment by emaxx-google** [comment]
PTAL - unit tests added.

**Comment by emaxx-google** [comment]
> LGTM % nit
> re strict vs relaxed condition - I suppose it depends on the point of view - this implementation detects a superset of possible runs to be crash loops compared to Chrome. This should make the condition for being in a crash loop more relaxed (which is what I was thinking of), but the condition for not being in a crash loop more strict (I guess this is what you were referring to). Ultimately, it doesn't matter a lot.

I see your point, got it. I've reworded the comment a bit to avoid this ambiguity.
