### PR TITLE
Fix incorrect storage of user selection data

### LINKED ISSUE #57: App crash-restart loop caused by bad data stored for user selection
Steps to reproduce:
1. Install the Connector app.
2. Install at least two middleware apps that talk to the Connector app. Press "Allow" in both prompts about granting permissions to them.

Expected:
This works.

Actual:
The Connector app crashes and fails to start due to a fatal error during initialization. After several crash-restart loops, the browser disables the App.

Workaround:
Uninstall the Connector and install it back.

/cc @dskaram

### PR DESCRIPTION
**Pull request by emaxx-google**
The Connector app was incorrectly serializing the user selection data
when saving it in the local storage, in cases when the stored data
contained more than one item.

Besides corrupting the stored user selections, this bug was leading to
the app crashes and crash-restart loops, as the error was unrecoverable.

This fixes #57.

### CODE REVIEW

File: common/js/src/container-helpers.js [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+
+/** @const */
+var GSC = GoogleSmartCard;
+
+/**
+ * Converts the given Map to an Object.
+ * @param {!Map} map
+ * @return {!Object}
+ */
+GSC.ContainerHelpers.buildObjectFromMap = function(map) {
```
Comment (pavolmarko) [inline common/js/src/container-helpers.js]: I guess an alternative way to put it would be:
```
function (map) {
    let obj = {};
    for (let [k,v] of map) {
        obj[k] = v;
    }
    return obj;
}
```

Would that maybe be clearer than going from `map` -> `[[key1, value1], [key2, value2], ..]` -> flattened array of `[key1, value1, key2, value2, ..]` -> `goog.object.create`? Or is there a reason why we _must_ use goog.object.create?

Comment (pavolmarko) [inline common/js/src/container-helpers.js]: What (should happen or) happens if the Map has a key that is not a string? Should we test that?

File: third_party/pcsc-lite/naclport/server_clients_management/build/js_unittests/Makefile [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+include ../../../../../../common/make/common.mk
+
+include $(COMMON_DIR_PATH)/make/js_building_common.mk
+
+include $(COMMON_DIR_PATH)/js/include.mk
+include ../../include.mk
+
+
+JS_COMPILER_INPUT_PATHS := \
+	$(PCSC_LITE_SERVER_CLIENTS_MANAGEMENT_JS_COMPILER_INPUT_DIR_PATHS) \
```
Comment (pavolmarko) [inline third_party/pcsc-lite/naclport/server_clients_management/build/js_unittests/Makefile]: Where does this come from? I don't understand this (but my Makefile knowledge is limited :) )

File: third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js [hunk 3]
```diff
@@ -0,0 +1,288 @@
...
+ */
+function setUpChromeStorageMock(
+    mockControl, propertyReplacer, fakeInitialData, expectedDataToBeWritten) {
+  propertyReplacer.set(
+      chrome, 'storage',
+      {local: {
+         get: mockControl.createFunctionMock('chrome.storage.local.get'),
+         set: mockControl.createFunctionMock('chrome.storage.local.set')}});
+
+  /** @type {?} */ chrome.storage.local.get;
```
Comment (pavolmarko) [inline third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js]: Why do we need this (and the same for .set)?
Is it to tell the closure compiler that these exist?

File: third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js [hunk 4]
```diff
@@ -0,0 +1,288 @@
...
+  chrome.storage.local.get(STORAGE_KEY, ignoreArgument).$does(
+      function(key, callback) {
+        callback(fakeInitialData);
+      });
+
+  /** @type {?} */ chrome.storage.local.set;
+  if (!goog.isNull(expectedDataToBeWritten))
+    chrome.storage.local.set(expectedDataToBeWritten);
```
Comment (pavolmarko) [inline third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js]: Does this already set up an expectation that .set will be called with the passed parameter ( and not called with anything else ), or do we need to call something like $does / $return / .. on it?

File: third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js [hunk 5]
```diff
@@ -0,0 +1,288 @@
...
+ * corresponding result.
+ */
+function setUpDialogMock(mockControl, mockedBehavior) {
+  /** @type {?} */
+  var mockedFunction = mockControl.createMethodMock(
+      GSC.PopupWindow.Server, 'runModalDialog');
+  var mockAction;
+  switch (mockedBehavior) {
+    case MockedDialogBehavior.NOT_RUN:
+      return;
```
Comment (pavolmarko) [inline third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js]: Should this fail somehow if the dialog is invoked when not expected?

File: third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js [hunk 6]
```diff
@@ -0,0 +1,288 @@
...
+ * @param {!goog.Promise} promise
+ * @return {!goog.Promise.<undefined>} A promise which is rejected when
+ * |promise| gets resolved, and resolved (with no data) when |promise| is
+ * rejected.
+ */
+function negatePromise(promise) {
+  return promise.then(function() {
+    fail('Unexpected successful response');
+  }, function() {
+    // Do not pass on the rejection.
```
Comment (pavolmarko) [inline third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js]: I'd have expected a resolve() call here -- does this not just ignore the rejection?

File: third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js [hunk 7]
```diff
@@ -293,8 +294,8 @@ UserPromptingChecker.prototype.storeUserSelection_ =
   this.localStoragePromiseResolver_.promise.then(
```
Comment (pavolmarko) [inline third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js]: (I'm too stupid to add the comment where it actually belongs)
Do we need to explicitly ignore garbage values in 
|contents| in localStorageLoadedCallback_ now (if written by a buggy previous version)?

File: common/js/src/container-helpers.js (hunk 1 above)
Comment (emaxx-google) [reply common/js/src/container-helpers.js]: Great point! Indeed, my original attempt in the functional style is failing compared to an ad-hoc approach.

Comment (emaxx-google) [reply common/js/src/container-helpers.js]: Good point, added an assertion (I think it's reasonable to assume only strings and numbers to be passed here by a valid code) and tests.

File: third_party/pcsc-lite/naclport/server_clients_management/build/js_unittests/Makefile (hunk 2 above)
Comment (emaxx-google) [reply third_party/pcsc-lite/naclport/server_clients_management/build/js_unittests/Makefile]: It comes from ../../include.mk. I've added a short comment for this piece.

File: third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js (hunk 3 above)
Comment (emaxx-google) [reply third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js]: The problem is that compiler actually knows them and verifies against the real signatures, which leads to errors as there's no "$does" property in the function's return value.
Added a comment on that.

File: third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js (hunk 4 above)
Comment (emaxx-google) [reply third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js]: Nope, the expectation is already set up. For instance, the tests fail if I repeat this line.

File: third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js (hunk 5 above)
Comment (emaxx-google) [reply third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js]: It will - by default, a function mock expects to be not called at all.

File: third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js (hunk 6 above)
Comment (emaxx-google) [reply third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker-unittests.js]: Maybe I misunderstood the question, but there's no resolve() method on the promise; and returning undefined from this function should resolve the resulting promise - according to the docs:

"If the Promise is rejected, the onRejected callback will be invoked with the rejection reason as argument, and the child Promise will be resolved with the return value or rejected with the thrown value of the callback."

File: third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js (hunk 7 above)
Comment (emaxx-google) [reply third_party/pcsc-lite/naclport/server_clients_management/src/permissions_checking/user-prompting-checker.js]: Yes, that's a good suggestion, we should not crash due to anything in the externally stored data. I was actually planning to do this, but in a follow-up change.

**Comment by emaxx-google** [comment]
PTAL.

**Comment by emaxx-google** [comment]
Thanks!
